dist: xenial
addons:
  chrome: stable
branches:
  only:
  - master
language: node_js
node_js: lts/*
install:
- npm install
script:
- npm run test
before_deploy: "mv public demo"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
